### ISSUE TITLE
Change API to more closely match threadly's java API?

### ISSUE THREAD

**Issue by jentfoo** [threadly/python-threadly#2]
What's your thoughts on renaming some things to more closely match the API in java?  Hopefully with the goal of making it easier for someone to use both.  Some examples I saw are:
- Rename "Executor" into "Scheduler"
- Change Executor.removeScheduled to just Executor.remove
- Change Executor.shutdown to Executor.shutdownNow (as the behavior of the shutdown is closer to shutdownNow, in the java API, shutdown will still allow queued tasks to finish, shutdownNow stops immediately (but does not interrupt running tasks))
- Change KeyRunner into "TaskDistributor"....Although I kinda like the name "KeyExecutorDistributor", maybe we should rename both the java and the python API into that?  Thoughts?
- Change Clock.accurateTime to Clock.accurateTimeMillis

Let me know your thoughts on each one.  Also definetly let me know your thoughts on changing the java API TaskExecutorDistributor into KeyExecutorDistributor, and change TaskSchedulerDistributor into KeySchedulerDistributor.

**Comment by lwahlmeier** [comment]
So in the new version I will be doing the following:

Renamed the Executor to Scheduler, but have an empty Executor class that extends Scheduler for backwards compatability.

changed removeScheduled to remove

Now have both shutdown and shutdownNow

Leaving keyRunner the same since its more of an internal only object no one lese should use

Added a clock_accurate_time_millis, but also have it not in millis
